## Source: https://github.com/rougier/numpy-100/

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a = np.zeros(10)

a

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a = np.zeros(100)

a.nbytes  ## 800 == 100 * 8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
## np.info or trough IPython introspection

np.info(np.random.random)

In [ ]:
# Or

np.random.random?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a = np.zeros(10)
a[4] = 1

a

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a = np.arange(10, 50)

a

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a = np.arange(1, 11)

print(a)

a = a[::-1]

print(a)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)

matrix_3x3

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a = np.array([1, 2, 0, 0, 4, 0])

indices_of_non_zero_elements = np.nonzero(a != 0)

indices_of_non_zero_elements

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity_matrix_3x3 = np.eye(3)

identity_matrix_3x3

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a = np.random.standard_normal(3**3).reshape(3, 3, 3)  # Standard Normal distribution
print(a, end='\n\n\n\n')

b = np.random.uniform(low=0, high=1, size=3**3).reshape(3, 3, 3)  # Uniform distribution
print(b)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
array_10x10 = np.random.uniform(low=0, high=100, size=10*10).reshape(10, 10).astype('int32')

print(array_10x10)
print(array_10x10.min())
print(array_10x10.max())

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a = np.random.random(30)

a.mean()

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
from functools import reduce

# Create shape tuple and evaluate its product
shape = (5, 5)
shape_product = reduce(lambda x, y: x * y, shape)

a = np.zeros(shape, dtype=np.int32)

a[0] = 1  # Fill first line
a[a.shape[0] - 1] = 1  ## Fill last line

a[:, 0] = 1  ## Fill first column
a[:, a.shape[1] - 1] = 1  ## Fill last column

print(a)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.arange(1, 10).reshape(3, 3)
print(a, end='\n\n')

a[0] = 0  # Fill first line
a[a.shape[0] - 1] = 0  ## Fill last line

a[:, 0] = 0 ## Fill first column
a[:, a.shape[1] - 1] = 0 # Fill last column

print(a)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix_5x5 = np.zeros(shape=(5,5))
print(matrix_5x5)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix_8x8 = np.zeros(shape=(8,8), dtype=np.int32)
print(matrix_8x8, end='\n\n')

matrix_8x8[::2, ::2] = 1
matrix_8x8[1::2, 1::2] = 1

print(matrix_8x8)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix_5x3 = np.random.randint(low=0, high=101, size=(5, 3))
matrix_3x2 = np.random.randint(low=0, high=101, size=(3, 2))

print(matrix_5x3, end='\n\n')
print(matrix_3x2, end='\n\n')

matrix_product = np.matmul(matrix_5x3, matrix_3x2)

print(matrix_product)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array = np.random.randint(low=0, high=12, size=20)
print(array, end='\n\n')

condition = (3 <= array) & (array <= 8)

array[condition] *= -1

print(array)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```


-1 + 0 + 1 + 2 + 3 + 4 = 9 and
0 + 1 + 2 + 3 + 4 = 10

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array_1 = np.random.randint(low=0, high=15, size=10)
array_2 = np.random.randint(low=0, high=15, size=10)

print(sorted(array_1), end='\n\n')
print(sorted(array_2), end='\n\n')

intersection = np.intersect1d(array_1, array_2)

print(sorted(intersection))

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)ndarray

In [ ]:
array = np.random.normal(loc=100, scale=3, size=10)
print(array, end='\n\n')

print(array // 1, end='\n\n')
print(array.astype(np.int32), end='\n\n')
print(np.trunc(array), end='\n\n')
print(np.floor(array), end='\n\n')

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix_5x5 = np.empty((5, 5), dtype=np.int32)
matrix_5x5[:] = np.arange(5)
matrix_5x5

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
number_of_attempts = 0
while True:
    a = np.random.randint(low=1, high=11, size=5)
    b = np.random.randint(low=1, high=11, size=5)

    number_of_attempts += 1  # Final number of attempts should be around (high-low)**5 at average
    if number_of_attempts % 10_000 == 0:
        print(f'{number_of_attempts:_}')

    if (a == b).all():
        break

print(a)
print(b)
print(number_of_attempts)


In [ ]:
number_of_simulations = 50
array_number_of_attempts = np.empty(shape=number_of_simulations)

for i in range(number_of_simulations):
    number_of_attempts = 0
    while True:
        a = np.random.randint(low=1, high=11, size=4)
        b = np.random.randint(low=1, high=11, size=4)

        number_of_attempts += 1  # Final number of attempts should be around (high-low)**5 at average
        if number_of_attempts % 10_000 == 0:
            print(f'{number_of_attempts:_}')

        if (a == b).all():
            print(a)
            print(b)
            break
    array_number_of_attempts[i] = number_of_attempts

print(array_number_of_attempts.shape)
print(f'{array_number_of_attempts.mean():_}')


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
array = np.random.random(size=10)
print(array, end='\n\n')

array[np.where(array == array.max())] = 0
print(array)
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
integer_types_to_be_examined = (np.int8, np.int16, np.int32, np.int64)

for dtype in integer_types_to_be_examined:
    print(np.iinfo(dtype).min, np.iinfo(dtype).max)
print()

float_types_to_be_examined = (np.float32, np.float64, np.longfloat)

for dtype in float_types_to_be_examined:
    print(np.finfo(dtype).min, np.finfo(dtype).max, np.finfo(dtype).eps)


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
array = np.arange(10)

print(array)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [8]:
array = np.random.randint(low=1, high=11, size=10)
print(array)

scalar = np.random.randint(low=0, high=20)
print(scalar)

index_of_closest_value = np.abs(array - scalar).argmin()
print(array[index_of_closest_value])

[2 6 9 6 3 5 2 3 9 8]
0
2


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
# Short answer: np.ndenumerate

# Example

array = np.arange(10)

for index, value in np.ndenumerate(array):
    print(index, value)
print()

matrix = np.random.random((3, 3))

for index, value in np.ndenumerate(matrix):
    print(index, value)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
matrix = np.random.randint(low=0, high=10, size=(3, 3))
print(matrix, matrix.dtype, end='\n\n')

row_means = matrix.mean(axis=1)[:, np.newaxis]
print(row_means, end='\n\n')

matrix = matrix - row_means
print(matrix, matrix.dtype)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
matrix = np.random.randint(low=0, high=10, size=(5, 5))
print(matrix, end='\n\n')

column_index = np.random.randint(low=0, high=matrix.shape[1])
print(f'{column_index = }\n')

matrix[:, column_index].sort()
print(matrix)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
matrix = np.random.binomial(1, 0.3, (5, 5))
print(matrix)

matrix_has_null_column = ~(matrix.any(axis=0).all())
print(f'{matrix_has_null_column = }')

if matrix_has_null_column:
    indices_of_null_columns = np.where(~(matrix.any(axis=0)))
    print('indices of null columns: ', end='')
    for index in indices_of_null_columns:
        print(index, end=' ')

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [10]:
array_length = 5

array = np.arange(array_length)
print(f'{array = }\n')

indices = np.random.randint(low=0, high=array_length, size=array_length)
print(f'{indices = }\n')

# unique_indices = np.unique(indices)
# print(f'{unique_indices = }\n')

# If we want to discard repeated indices:
print(f'Discarding repeated indices: {array[indices] + 1}')

# If we do not want to discard repeated indices:
np.add.at(array, indices, 1)
print(f'Not discarding repeated indices: {array}')

array = array([0, 1, 2, 3, 4])

indices = array([0, 4, 3, 4, 4])

Discarding repeated indices: [1 5 4 5 5]
Not discarding repeated indices: [1 1 2 4 7]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [12]:
size_of_dimensions = 3
four_dimensional_array = np.ones((size_of_dimensions, ) * 4)
print(four_dimensional_array.shape, end='\n\n')

crazy_sum = four_dimensional_array.sum(axis=(-1,-2)) # or sum(axis=(2, 3))
print(crazy_sum)

(3, 3, 3, 3)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
matrix = np.random.randint(low=0, high=10, size=(5, 5))
print(matrix)

print("\nLet's swap the first row by the last row...")

last_row_index = matrix.shape[0] - 1

matrix[[0]], matrix[[last_row_index]] = matrix[[last_row_index]], matrix[[0]]
print(matrix)

#### 83. How to find the most frequent value in an array?

In [41]:
array_length = 10
array = np.random.randint(low=0, high=10, size=array_length)
print(f'{array = }')

bincount = np.bincount(array)
most_frequent_value = bincount.argmax()
indices_of_most_frequent_value = np.where(array == most_frequent_value)
frequency_of_most_frequent_value = np.count_nonzero(array == most_frequent_value)

print(f'\n{bincount = }')
print(f'{most_frequent_value = }')
print(f'{indices_of_most_frequent_value = }')
print(f'{frequency_of_most_frequent_value = }')

array = array([4, 8, 0, 0, 9, 8, 5, 4, 9, 8])

bincount = array([2, 0, 0, 0, 2, 1, 0, 0, 3, 2])
most_frequent_value = 8
indices_of_most_frequent_value = (array([1, 5, 9]),)
frequency_of_most_frequent_value = 3


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
array = np.random.randint(low=0, high=20, size=10)
print(f'{array = }')

n = 3
print(f'{n = }')

n_largest_values = np.sort(array)[:3]
print(f'{n_largest_values = }')

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
matrix = np.random.randint(low=0, high=2, size=(10, 3))
print(matrix)

row_indices = np.where