## Source: https://github.com/rougier/numpy-100/

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

np

<module 'numpy' from '/home/karlos/miniconda3/envs/pydata-book/lib/python3.10/site-packages/numpy/__init__.py'>

#### 2. Print the numpy version and the configuration (★☆☆)

In [19]:
print(np.__version__)
print(np.show_config())

1.23.3
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/karlos/miniconda3/envs/pydata-book/lib']
    include_dirs = ['/home/karlos/miniconda3/envs/pydata-book/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/karlos/miniconda3/envs/pydata-book/lib']
    include_dirs = ['/home/karlos/miniconda3/envs/pydata-book/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/karlos/miniconda3/envs/pydata-book/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/karlos/miniconda3/envs/pydata-book/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/karlos/mi

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10)

a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
a = np.zeros(100)

a.nbytes  ## 800 == 100 * 8

800

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
## np.info or trough IPython introspection

np.info(np.random.random)

random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.


In [20]:
# Or

np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10)
a[4] = 1

a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10, 50)

a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
a = np.arange(1, 11)

print(a)

a = a[::-1]

print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
matrix_3x3 = np.arange(9).reshape(3, 3)

matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
a = np.array([1, 2, 0, 0, 4, 0])

indices_of_non_zero_elements = np.nonzero(a != 0)

indices_of_non_zero_elements

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
identity_matrix_3x3 = np.eye(3)

identity_matrix_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
a = np.random.standard_normal(3**3).reshape(3, 3, 3)  # Standard Normal distribution
print(a, end='\n\n\n\n')

b = np.random.uniform(low=0, high=1, size=3**3).reshape(3, 3, 3)  # Uniform distribution
print(b)

[[[-0.10754618 -0.09605857 -0.27639388]
  [ 0.26848683  2.33201316  0.50955832]
  [ 0.14491663  0.18650524  0.72925813]]

 [[-1.20028652 -0.11056982  0.08777806]
  [ 0.01876635  0.41837588  0.89972846]
  [-1.24507575  0.5727807  -1.51463893]]

 [[-1.44691454 -0.10259617 -0.62008803]
  [-0.64187449  0.93428547  1.26107254]
  [-0.54229001  1.0279294  -0.70805881]]]



[[[0.09116132 0.7962023  0.44304649]
  [0.58054999 0.8000735  0.62641654]
  [0.91267696 0.40447258 0.60092198]]

 [[0.3435858  0.44135582 0.98567749]
  [0.35950338 0.29531179 0.41691793]
  [0.09878014 0.65642559 0.9092522 ]]

 [[0.803904   0.41720703 0.55972106]
  [0.2279389  0.45001822 0.0963655 ]
  [0.9590468  0.5844648  0.05625942]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
array_10x10 = np.random.uniform(low=0, high=100, size=10*10).reshape(10, 10).astype('int32')

print(array_10x10)
print(array_10x10.min())
print(array_10x10.max())

[[39 43 68 36 77 44 64 41 66 49]
 [27 24 48 28 96 44 72 46  9 95]
 [13 33 77 88 92 39 87 69 63 67]
 [28 29 48 88 69 81 69 27 66 11]
 [47 61 14 26 46 67 60 27  1 70]
 [80 80 51 29 77 69 13 44 11 51]
 [63 67 46 52 98 40 95 98 71 33]
 [39 53 30 99 98 38 36 63 61 42]
 [49 86 32  6 16 99 15  8 85 48]
 [11 61 25 79  4  5 40  0 86 23]]
0
99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
a = np.random.random(30)

a.mean()

0.5896146895930964

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [21]:
from functools import reduce

# Create shape tuple and evaluate its product
shape = (5, 5)
shape_product = reduce(lambda x, y: x * y, shape)

a = np.zeros(shape, dtype=np.int32)

a[0] = 1  # Fill first line
a[a.shape[0] - 1] = 1  ## Fill last line

a[:, 0] = 1  ## Fill first column
a[:, a.shape[1] - 1] = 1  ## Fill last column

print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
a = np.arange(1, 10).reshape(3, 3)
print(a, end='\n\n')

a[0] = 0  # Fill first line
a[a.shape[0] - 1] = 0  ## Fill last line

a[:, 0] = 0 ## Fill first column
a[:, a.shape[1] - 1] = 0 # Fill last column

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 0 0]
 [0 5 0]
 [0 0 0]]
