## Source: https://github.com/rougier/numpy-100/

#### 1. Import the numpy package under the name `np` (★☆☆)

In [56]:
import numpy as np

np

<module 'numpy' from 'C:\\Users\\karlos.silva\\Anaconda3\\envs\\pydata-book\\lib\\site-packages\\numpy\\__init__.py'>

#### 2. Print the numpy version and the configuration (★☆☆)

In [57]:
print(np.__version__)
print(np.show_config())

1.23.3
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/karlos.silva/Anaconda3/envs/pydata-book\\Library\\lib']
    include_dirs = ['C:/Users/karlos.silva/Anaconda3/envs/pydata-book\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/karlos.silva/Anaconda3/envs/pydata-book\\Library\\lib']
    include_dirs = ['C:/Users/karlos.silva/Anaconda3/envs/pydata-book\\Library\\include']
    language = f77
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['C:/Users/karlos.silva/Anaconda3/envs/pydata-book\\Library\\lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/karlos.silv

#### 3. Create a null vector of size 10 (★☆☆)

In [58]:
a = np.zeros(10)

a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [59]:
a = np.zeros(100)

a.nbytes  ## 800 == 100 * 8

800

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [60]:
## np.info or trough IPython introspection

np.info(np.random.random)

random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.


In [61]:
# Or

np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [62]:
a = np.zeros(10)
a[4] = 1

a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [63]:
a = np.arange(10, 50)

a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [64]:
a = np.arange(1, 11)

print(a)

a = a[::-1]

print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [65]:
matrix_3x3 = np.arange(9).reshape(3, 3)

matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [66]:
a = np.array([1, 2, 0, 0, 4, 0])

indices_of_non_zero_elements = np.nonzero(a != 0)

indices_of_non_zero_elements

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [67]:
identity_matrix_3x3 = np.eye(3)

identity_matrix_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [68]:
a = np.random.standard_normal(3**3).reshape(3, 3, 3)  # Standard Normal distribution
print(a, end='\n\n\n\n')

b = np.random.uniform(low=0, high=1, size=3**3).reshape(3, 3, 3)  # Uniform distribution
print(b)

[[[-7.82271017e-01  2.97823927e-01 -1.14213756e+00]
  [ 1.56653283e+00  1.49958582e+00 -1.28906030e+00]
  [ 1.08636023e+00 -1.40726360e+00  3.33623491e-01]]

 [[ 9.81297628e-01 -7.25438181e-01  7.08937951e-01]
  [-4.36559348e-04 -4.53177269e-01  1.10379175e-01]
  [ 2.73952526e-01 -4.09370507e-01  1.65844141e-01]]

 [[-3.86998563e-01 -2.61954983e+00 -5.91219375e-02]
  [-9.80135977e-01  1.06376881e-01  3.99159478e-01]
  [-1.44471290e+00 -1.55723088e+00  8.50376577e-01]]]



[[[0.10516951 0.34613311 0.05200194]
  [0.07589753 0.97685497 0.77657538]
  [0.66162895 0.01991299 0.67421817]]

 [[0.49519811 0.28152514 0.99727427]
  [0.95250956 0.05851441 0.73735383]
  [0.45355471 0.99893284 0.53351615]]

 [[0.72912492 0.78486735 0.40062719]
  [0.91474453 0.23055895 0.80928136]
  [0.45130865 0.79412207 0.21037819]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [69]:
array_10x10 = np.random.uniform(low=0, high=100, size=10*10).reshape(10, 10).astype('int32')

print(array_10x10)
print(array_10x10.min())
print(array_10x10.max())

[[18  0 26 19 44 82 90 62 19 55]
 [72 77 33 38 59 20 55 14 70 23]
 [74 58 18 81 14 54 37 81 19 68]
 [83 26 32  0 47 73 49 60 93 21]
 [99 90 10  2 94 26 13 38 30 66]
 [97 80 79 73 47 58 54 19 50  2]
 [60 94 60 25 97 19 24 33 19 31]
 [24 62 93 96 38 37 24  7 41 81]
 [62 97 57 10 19  4 18 40 64 33]
 [21 95 81  5 61  5 91 95 80 45]]
0
99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [70]:
a = np.random.random(30)

a.mean()

0.4936640081640873

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [71]:
from functools import reduce

# Create shape tuple and evaluate its product
shape = (5, 5)
shape_product = reduce(lambda x, y: x * y, shape)

a = np.zeros(shape, dtype=np.int32)

a[0] = 1  # Fill first line
a[a.shape[0] - 1] = 1  ## Fill last line

a[:, 0] = 1  ## Fill first column
a[:, a.shape[1] - 1] = 1  ## Fill last column

print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [72]:
a = np.arange(1, 10).reshape(3, 3)
print(a, end='\n\n')

a[0] = 0  # Fill first line
a[a.shape[0] - 1] = 0  ## Fill last line

a[:, 0] = 0 ## Fill first column
a[:, a.shape[1] - 1] = 0 # Fill last column

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 0 0]
 [0 5 0]
 [0 0 0]]


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [73]:
matrix_5x5 = np.zeros(shape=(5,5))
print(matrix_5x5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [84]:
matrix_8x8 = np.zeros(shape=(8,8), dtype=np.int32)
print(matrix_8x8, end='\n\n')

matrix_8x8[::2, ::2] = 1
matrix_8x8[1::2, 1::2] = 1

print(matrix_8x8)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [107]:
matrix_5x3 = np.random.randint(low=0, high=101, size=(5, 3))
matrix_3x2 = np.random.randint(low=0, high=101, size=(3, 2))

print(matrix_5x3, end='\n\n')
print(matrix_3x2, end='\n\n')

matrix_product = np.matmul(matrix_5x3, matrix_3x2)

print(matrix_product)

[[65 21 61]
 [13 86 76]
 [15 74 96]
 [ 0 21 34]
 [18 34 67]]

[[82 34]
 [28 70]
 [37 98]]

[[ 8175  9658]
 [ 6286 13910]
 [ 6854 15098]
 [ 1846  4802]
 [ 4907  9558]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [117]:
array = np.random.randint(low=0, high=12, size=20)
print(array, end='\n\n')

condition = (3 <= array) & (array <= 8)

array[condition] *= -1

print(array)

[ 5  0  8  0  8  0  7  2  4  2  4  7  8 11  6  3  0  1  9 11]

[-5  0 -8  0 -8  0 -7  2 -4  2 -4 -7 -8 11 -6 -3  0  1  9 11]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```


-1 + 0 + 1 + 2 + 3 + 4 = 9 and
0 + 1 + 2 + 3 + 4 = 10

#### 30. How to find common values between two arrays? (★☆☆)

In [151]:
array_1 = np.random.randint(low=0, high=15, size=10)
array_2 = np.random.randint(low=0, high=15, size=10)

print(sorted(array_1), end='\n\n')
print(sorted(array_2), end='\n\n')

intersection = np.intersect1d(array_1, array_2)

print(sorted(intersection))

[1, 2, 5, 5, 8, 9, 10, 12, 14, 14]

[2, 3, 5, 5, 5, 6, 7, 7, 8, 12]

[2, 5, 8, 12]
